# Generated by Django 6.0.2 on 2026-02-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_generalquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='message',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(),
        ),
    ]
